#FROM arm32v7/python:3.6-jessie
FROM raspbian/jessie
MAINTAINER "Anton Kirilenko" <antony.kirilenko@gmail.com>

ENV QEMU_EXECVE 1

COPY qemu/cross-build-end qemu/cross-build-start qemu/qemu-arm-static qemu/sh-shim /usr/bin/

RUN ["cross-build-start"]

#WORKDIR /tmp/

RUN apt-get update && apt-get install -y \
    build-essential \
    libsdl2-dev \
    libsdl2-image-dev \
    libsdl2-mixer-dev \
    libsdl2-ttf-dev \
    libportmidi-dev \
    libswscale-dev \
    libavformat-dev \
    libavcodec-dev \
    zlib1g-dev


# Installing python 3.6
RUN apt-get install -y tk-dev libncurses5-dev libncursesw5-dev \
    libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev \
    libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev

RUN wget https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tar.xz
RUN tar xf Python-3.6.4.tar.xz
RUN cd Python-3.6.4 && ./configure && make -j `grep -c ^processor /proc/cpuinfo` && make altinstall
RUN cd ..
RUN rm -rf Python-3.6.4 && rm -f Python-3.6.4.tar.xz


RUN pip3.6 install Cython==0.25.2
#TODO
RUN apt install -y git
RUN pip3.6 install kivy==1.10.0

COPY requirements.txt /tmp/requirements.txt
RUN pip3.6 install -r /tmp/requirements.txt --no-cache-dir

ENV READTHEDOCS True
RUN pip3.6 install 'picamera[array]==1.13'

RUN apt-get install --reinstall -y libraspberrypi-bin libraspberrypi-dev libraspberrypi-doc libraspberrypi0

RUN apt install -y libmtdev1

#RUN apt install -y libjpeg-dev libtiff5-dev libjasper-dev libpng12-dev





#RUN apt install -y libatlas-base-dev gfortran

#RUN pip3.6 install opencv-python==3.4.0.12
#RUN apt install -y unzip cmake



#RUN wget -q https://github.com/opencv/opencv/archive/3.4.1.zip

#RUN unzip 3.4.1.zip

#RUN wget -q https://github.com/opencv/opencv_contrib/archive/master.zip
#RUN unzip master.zip

#RUN mkdir opencv-3.4.1/build/
#RUN cd opencv-3.4.1/build/ && cmake -D CMAKE_BUILD_TYPE=RELEASE \
#    -D CMAKE_INSTALL_PREFIX=/usr/local \
#    -D PYTHON_DEFAULT_EXECUTABLE=python3.6 \
#    -D PYTHON_EXECUTABLE=python3.6 \
#    -D OPENCV_EXTRA_MODULES_PATH=/tmp/opencv_contrib-master/modules \
#    /tmp/opencv-3.4.1

#RUN cd opencv-3.4.1/build/ && make -j `grep -c ^processor /proc/cpuinfo`

RUN rm -rf /tmp/*
RUN ["cross-build-end"]
