FROM arm32v7/python:3.5-jessie
MAINTAINER "Anton Kirilenko" <antony.kirilenko@gmail.com>

ENV QEMU_EXECVE 1

COPY qemu/cross-build-end qemu/cross-build-start qemu/qemu-arm-static qemu/sh-shim /usr/bin/

RUN ["cross-build-start"]

RUN apt-get update && apt-get install -y \
    build-essential \
    libsdl2-dev \
    libsdl2-image-dev \
    libsdl2-mixer-dev \
    libsdl2-ttf-dev \
    libportmidi-dev \
    libswscale-dev \
    libavformat-dev \
    libavcodec-dev \
    zlib1g-dev

RUN pip3 install Cython==0.25.2
RUN pip3 install kivy==1.10.0

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt --no-cache-dir

RUN ["cross-build-end"]
